# Generated by Django 4.2 on 2024-07-02 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_category_post_notification_comment_bookmark'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='like',
            new_name='likes',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='view',
            new_name='views',
        ),
    ]
